<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create new Product</title>
</head>
<body>

<h1>Create new Product</h1>
<h4><?=$message ?></h4>
<h4><?=$message1 ?></h4>
<h4><?=$message2 ?></h4>
<?=out()?>


<form method='post' enctype="multipart/form-data">
    <input type="text" name="title" placeholder="title" value='<?=$title ?>'> <br>
    <input type="text" name="price" placeholder="price" value="<?=$price ?>"> <br>
    <textarea name="description" placeholder="description"><?=$description ?></textarea> <br>

    <input type="file" name="image"> <br>

    <button type='submit'>Go</button>
</form>


</body>
</html>