<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>revert</title>
</head>
<body>
<?=$message?>

<form method="post">
    <label>input your string </label>
    <input type="text" name="string">
    <button type="submit">Go</button>

</form>

</body>
</html>